### PR TITLE
ARM: DT: sun5i-r8-chip: Enable PWM for the C.H.I.P.

### PR DESCRIPTION
**Pull request by hrishikesh195**
Signed-off-by: Hrishikesh Tapaswi <hrishikesh195@yahoo.com>

### CODE REVIEW

**Comment by hrishikesh195** [comment]
It appears that there already is PWM support (in nextthing/4.4/next) but it doesn't get exported in sysfs. After enabling it for the CHIP with this patch, I'm able to see the device in sysfs and control a servo, for example -

```
root@cheetos:/sys/class/pwm/pwmchip0# echo 0 > export 
root@cheetos:/sys/class/pwm/pwmchip0# ls
device	export	npwm  power  pwm0  subsystem  uevent  unexport
root@cheetos:/sys/class/pwm/pwmchip0# cd pwm0/
root@cheetos:/sys/class/pwm/pwmchip0/pwm0# ls
duty_cycle  enable  period  polarity  power  uevent
root@cheetos:/sys/class/pwm/pwmchip0/pwm0# cat duty_cycle 
1000000
root@cheetos:/sys/class/pwm/pwmchip0/pwm0# echo "normal" > polarity 
root@cheetos:/sys/class/pwm/pwmchip0/pwm0# cat polarity 
normal
root@cheetos:/sys/class/pwm/pwmchip0/pwm0# cat period 
20000000
root@cheetos:/sys/class/pwm/pwmchip0/pwm0# echo 1500000 > duty_cycle 
root@cheetos:/sys/class/pwm/pwmchip0/pwm0# 
root@cheetos:/sys/class/pwm/pwmchip0/pwm0# echo 1 > enable 
root@cheetos:/sys/class/pwm/pwmchip0/pwm0# echo 0 > enable 
root@cheetos:/sys/class/pwm/pwmchip0/pwm0# cd ..
root@cheetos:/sys/class/pwm/pwmchip0# echo 0 > unexport 
root@cheetos:/sys/class/pwm/pwmchip0#  
```

**Comment by hrishikesh195** [comment]
Looks like there was a rebase and the commits in nextthing/4.4/next have changed. I'll apply my change on top of the branch and update the pull request. Is nextthing/4.4/next the right branch to base my change on? Or should I pick a different branch?

**Comment by mripard** [comment]
Hi,

Unfortunately, we won't merge this patch. This enforces a default usage that other users might disagree with.

Fortunately, with the 4.4 kernel in our next release, we're going to have a way to add new nodes to the DT, which should cover most of the use cases.

Thanks for your patch though!
Maxime

**Comment by hrishikesh195** [comment]
@mripard Just wanted to circle back on this. With 4.4 having been released, I was wondering if there's a way to add nodes to the DT in order to use PWM. Is so, could you point me to some instructions for it?

**Comment by ericterpstra** [comment]
I would also like to know how to do this.  Any resolution? People on the forums are saying it's not possible to use PWM0 without recompiling a kernel.

**Comment by funkycode** [comment]
@mripard Any update on PWM?

**Comment by combs** [comment]
there is a pretty easy-to-use Python interface for loading a PWM DTB overlay here...
https://github.com/xtacocorex/CHIP_IO

**Pull request closed without merging**
