### PR TITLE
DTS: sun5i-r8-chip add SPI2

### PR DESCRIPTION
**Pull request by vmayoral**

### CODE REVIEW

**Comment by mripard** [comment]
Hi,

We don't want to enforce particular muxing on the pins themselves, since they can be used for a number of usages, including GPIOs.

Thanks for your contribution though!
Maxime

**Comment by vmayoral** [comment]
No problem @mripard! Thanks for reviewing it.

I'm struggling to get a second chip select with SPI and the R8. Maybe you can give me a hand here?
While using [this syntax](https://github.com/erlerobot/CHIP-linux/blob/a9237e363ebc74acc662fb2150df2d3df5535494/arch/arm/boot/dts/sun5i-r8-chip.dts#L484) i can perfectly talk to CS0 (and obviously not to CS1), [this other one](https://github.com/erlerobot/CHIP-linux/blob/03f461a129757e6150788fad2751f4a23d8e4cfc/arch/arm/boot/dts/sun5i-r8-chip.dts#L484) doesn't allow me to talk neither with CS0 nor with CS1 (which is what i was expecting).
Mind having a look?

**Comment by mripard** [comment]
Hmm, yes, I can see what you're trying to do, but it's not really the right way to do it.

Pinctrl is used to control the SoC pins muxing. Which means that it acts on what functions inside the SoC is routed to the pins of the SoC itself. It doesn't have any kind of iteraction with a particular subsystem (SPI in this case). It just makes sure that the SPI controller will be able to "talk" to the outside world.

What you're trying to do is use a chip select using the GPIO through the GPIO expander. This expander is outside of the SoC itself, so you shouldn't be pinctrl at all.

What you want to do though is use the cs-gpios property. You can have some documentation for that here https://www.kernel.org/doc/Documentation/devicetree/bindings/spi/spi-bus.txt

You'll probably want something like this
&spi2 {
        pinctrl-names = "default";
        pinctrl-0 = <&spi2_pins_a>, <&spi2_cs0_pins_a>;
        cs-gpios = <0>, <&xio 5 GPIO_ACTIVE_LOW>;

       <devices>;
};

Note that this is totally untested :)

**Comment by vmayoral** [comment]
Thanks @mripard,

Unfortunately, when describing the dts as you suggest the kernel dumps the following:
```
root@chip:/boot# dmesg|grep spi
[    1.360000] /soc@01c00000/spi@01c17000: could not get #gpio-cells for /soc@01c00000/pinctrl@01c20800/spi2_cs1@0
[    1.380000] sun4i-spi 1c17000.spi: cannot register SPI master
[    1.390000] [<c0402f14>] (clk_disable) from [<c0370644>] (sun4i_spi_runtime_suspend+0x18/0x3c)
[    1.390000] [<c0370644>] (sun4i_spi_runtime_suspend) from [<c0370b50>] (sun4i_spi_probe+0x1ac/0x248)
[    1.390000] [<c0370b50>] (sun4i_spi_probe) from [<c031d1f8>] (platform_drv_probe+0x44/0xa4)
[    1.870000] [<c040369c>] (clk_unprepare) from [<c037064c>] (sun4i_spi_runtime_suspend+0x20/0x3c)
[    1.890000] [<c037064c>] (sun4i_spi_runtime_suspend) from [<c0370b50>] (sun4i_spi_probe+0x1ac/0x248)
[    1.900000] [<c0370b50>] (sun4i_spi_probe) from [<c031d1f8>] (platform_drv_probe+0x44/0xa4)
[    2.090000] [<c0402f14>] (clk_disable) from [<c0370658>] (sun4i_spi_runtime_suspend+0x2c/0x3c)
[    2.090000] [<c0370658>] (sun4i_spi_runtime_suspend) from [<c0370b50>] (sun4i_spi_probe+0x1ac/0x248)
[    2.090000] [<c0370b50>] (sun4i_spi_probe) from [<c031d1f8>] (platform_drv_probe+0x44/0xa4)
[    2.590000] [<c040369c>] (clk_unprepare) from [<c0370660>] (sun4i_spi_runtime_suspend+0x34/0x3c)
[    2.600000] [<c0370660>] (sun4i_spi_runtime_suspend) from [<c0370b50>] (sun4i_spi_probe+0x1ac/0x248)
[    2.620000] [<c0370b50>] (sun4i_spi_probe) from [<c031d1f8>] (platform_drv_probe+0x44/0xa4)
[    2.830000] sun4i-spi: probe of 1c17000.spi failed with error -22
[   63.370000] [<c0066a6c>] (lock_acquire) from [<c05822fc>] (_raw_spin_lock_bh+0x40/0x50)
[   63.370000] [<c05822fc>] (_raw_spin_lock_bh) from [<bf06fe5c>] (rtw_alloc_macid+0x78/0x2bc [8723bs])
```
Any chance the spi2 definition at `sun5i.dtsi` should be modified somehow?

**Comment by mripard** [comment]
Remove it, as I already told you it doesn't make any sense
Le 5 nov. 2015 00:32, "Víctor Mayoral Vilches" <notifications@github.com> a
écrit :

**Comment by vmayoral** [comment]
Hi @mripard. I removed the previous `pintcrtl-0` definition and used the form you suggested:
```
/* Add support for SPI */
&spi2 {
	pinctrl-names = "default";
	pinctrl-0 = <&spi2_pins_a>, <&spi2_cs0_pins_a>;
	cs-gpios = <0>, <&spi2_cs1_pins_a>;
	status = "okay";

	spi2_0 {
		#address-cells = <1>;
		#size-cells = <0>;
		compatible = "spidev";
		reg = <0>;
		spi-max-frequency = <50000000>;
	};

	spi2_1 {
		#address-cells = <1>;
		#size-cells = <0>;
		compatible = "spidev";
		reg = <1>;
		spi-max-frequency = <50000000>;
	};
};
```
https://github.com/erlerobot/CHIP-linux/blob/c856012b2943cd211b7d105082ceaa0004654627/arch/arm/boot/dts/sun5i-r8-chip.dts#L482

Unfortunately this dts ends up in the error listed above. Am I missing something?

**Comment by vmayoral** [comment]
@mripard, silly me. Apologies. For some reason i missed the obvious thing.

After correctly applying the fix you suggested the kernel accepts the dtb but that second SPI CS still won't work. I'll keep looking at it and hook a scope to see what's going on. Thanks!

**Pull request closed without merging**
